- src/DependencyInjection/ShopApiExtension.php
- src/Resources/config/services.xml
This fix is needed to make request stateless. This is just a temporary solution because it would break Sylius Shop.
> [HOT-FIX] Temporary remove session cart subscriber

- src/Resources/config/app/config.yml
- tests/Application/app/config/config.yml
This file is useless because `fos_rest.format_listener.rules` has to be defined only once. It is already covered in README file
> [Config] Remove config file

- src/Resources/config/services.xml
- tests/Application/app/AppKernel.php
- tests/Application/app/config/config.yml
- tests/Application/app/config/routing.yml
- tests/Responses/Expected/cart/filled_cart_with_product_variant_summary_response.json
- tests/Responses/Expected/cart/filled_cart_with_simple_product_summary_response.json
- tests/Responses/Expected/cart/german_filled_cart_with_simple_product_summary_response.json
- tests/Responses/Expected/product/german_simple_product_details_page.json
- tests/Responses/Expected/product/limited_product_list_page.json
- tests/Responses/Expected/product/product_list_page.json
- tests/Responses/Expected/product/product_with_variant_details_page.json
- tests/Responses/Expected/product/simple_product_details_page.json
- tests/Responses/Expected/taxon/all_taxons_response.json
- tests/Responses/Expected/taxon/german_all_taxons_response.json
- tests/Responses/Expected/taxon/german_one_of_taxons_response.json
- tests/Responses/Expected/taxon/one_of_taxons_response.json
ShopBundle didn't work either because I was forced to remove one of its dependencies previously. Bringing back ShopBundle support can be defined as an issue, but I think it would be better to have two separate bundles working rather than only one.
> [Sylius] Remove ShopBundle from tests dependencies

- spec/Command/AddressOrderSpec.php
- spec/Command/ChooseShippingMethodSpec.php
- spec/Command/PickupCartSpec.php
- spec/Command/PutSimpleItemToCartSpec.php
- spec/Handler/AddressOrderHandlerSpec.php
- spec/Handler/ChooseShippingMethodHandlerSpec.php
- spec/Handler/PickupCartHandlerSpec.php
- spec/Handler/PutSimpleItemToCartHandlerSpec.php
- src/Command/AddressOrder.php
- src/Command/ChooseShippingMethod.php
- src/Command/PickupCart.php
- src/Command/PutSimpleItemToCart.php
- src/Controller/CartController.php
- src/Controller/Checkout/ChooseShippingMethodAction.php
- src/Controller/Checkout/ShowAvailableShippingMethodsAction.php
- src/Handler/ChooseShippingMethodHandler.php
- src/Handler/PickupCartHandler.php
- src/Handler/PutSimpleItemToCartHandler.php
- src/Resources/config/routing/checkout.yml
- src/Resources/config/services.xml
- src/Resources/config/services/controller.xml
- src/View/ShipmentMethodView.php
- tests/Application/app/config/config.yml
- tests/Controller/CheckoutAddressShopApiTest.php
- tests/Controller/CheckoutChooseShippingMethodApiTest.php
- tests/Controller/CheckoutShowAvailableShippingMethodsShopApiTest.php
- tests/Controller/CheckoutSummarizeShopApiTest.php
- tests/Responses/Expected/checkout/get_available_shipping_methods.json
Resolves #21 and #19
Based on #64 
There is a slight change in a choosing request. Instead of `PUT /cart/{token}/select-shipping` with the following body: 
```json
{
"shipments": [
{
"method": "DELIVERY_CODE"
}
]
}
```
I have decide for `PUT /cart/{token}/shipping/{shippingId}` with
```json
{
"method": "DELIVERY_CODE"
}
```
> [Checkout] Show and choose available shipping methods

- .travis.yml
- composer.json
- tests/Application/app/config/config.yml
Just a first commit from #140. Too many things happen there, it will be easier to do it step by step.
Based on #142
> [Maintenance] Drop PHP 5.6 and PHP 7.0 support

- src/Request/PutOptionBasedConfigurableItemToCartRequest.php
- src/Request/PutSimpleItemToCartRequest.php
- src/Request/PutVariantBasedConfigurableItemToCartRequest.php
- src/Resources/config/validation/PutSimpleItemToCartRequest.xml
- src/Resources/config/validation/PutVariantBasedConfigutableItemToCartRequest.xml
- tests/Responses/Expected/cart/validation_product_not_configurable_response.json
- tests/Responses/Expected/cart/validation_product_not_defined_response.json
- tests/Responses/Expected/cart/validation_product_not_exists_response.json
- tests/Responses/Expected/cart/validation_product_not_simple_response.json
- tests/Responses/Expected/cart/validation_product_variant_not_exists_response.json
We should also think about unifying keys between requests. Sometimes I have used `channel` sometimes `channelCode` for example. It should be fixed before release
> [Cart] More consistent validation message

- tests/Application/app/config/security.yml
Rest of firewalls names have hard spaces instead of dashes
> [Config] Make firewalls name more coherent

- composer.json
Too strict final class policy makes tests failing.
> Exclude doctrine/common >=2.8

- README.md
- composer.json
add composer suggestion nelmio/cors-bundle, 
update README for cors-bundle configuration
> add composer suggestions

- README.md
with this fix, it works for the add-to-cart post API on localhost with regular JSON payload, which doesn't need to be FormData
related to this issue https://github.com/nelmio/NelmioCorsBundle/issues/37
> fix nelmio_cors bundle config in the readme, 

- README.md
add allowed header authorization and allowed method options
need to permit cors preflight options, otherwise the JWT token could not be sent along the request like `/shop-api/me`, get always an 'Unauthorized header' error
> update nelmio_cors config,

- doc/swagger.yml
- src/Request/ChangeItemQuantityRequest.php
- src/Request/PutOptionBasedConfigurableItemToCartRequest.php
- src/Request/PutSimpleItemToCartRequest.php
- src/Request/PutVariantBasedConfigurableItemToCartRequest.php
- tests/Controller/CartChangeItemQuantityApiTest.php
- tests/Controller/CartPutItemToCartApiTest.php
- tests/Responses/Expected/cart/validation_quantity_not_defined_response.json
- tests/Responses/Expected/cart/validation_quantity_not_integer_response.json
PR does fix this issue: https://github.com/Sylius/SyliusShopApiPlugin/issues/235
> Get quantity from request as an integer.

- README.md
The CheckoutResolver should only be applied to the subpath of checkout, it would causes error in loading the root checkout path if enabled.
> Fix an issue in the configuration example which causes error in loading checkout page.

- .travis.yml
- composer.json
Sylius 1.0 is about to stop being supported in a few days (only receiving security fixes).
> Drop support for Sylius 1.0

- doc/swagger.yml
> Added more documentation to swagger

- src/Controller/CartController.php
I found an old controller that is not used anymore. So we can safely remove it.
> Removed unused cart controller

- doc/swagger.yml
Added swagger documentation for the address book.
> Added documentation for the address book

- src/Resources/config/routing.yml
- src/Resources/config/routing/cart.yml
- src/Resources/config/routing/checkout.yml
- src/Resources/config/routing/customer.yml
- src/Resources/config/routing/productByCode.yml
- src/Resources/config/routing/productBySlug.yml
- src/Resources/config/routing/productList.yml
- src/Resources/config/routing/register.yml
- src/Resources/config/routing/taxon.yml
- src/Resources/config/serializer/ProductView.yml
- src/Resources/views/Email/passwordReset.html.twig
- src/Resources/views/Email/verification.html.twig
- tests/Application/app/config/routing.yml
- tests/Application/app/config/security.yml
> Unified routing

- spec/Command/AddCouponSpec.php
- spec/Command/AddressOrderSpec.php
- spec/Command/ChangeItemQuantitySpec.php
- spec/Command/ChoosePaymentMethodSpec.php
- spec/Command/ChooseShippingMethodSpec.php
- spec/Command/CompleteOrderSpec.php
- spec/Command/DropCartSpec.php
- spec/Command/PickupCartSpec.php
- spec/Command/PutOptionBasedConfigurableItemToCartSpec.php
- spec/Command/PutSimpleItemToCartSpec.php
- spec/Command/PutVariantBasedConfigurableItemToCartSpec.php
- src/Command/AddCoupon.php
- src/Command/AddressOrder.php
- src/Command/ChangeItemQuantity.php
- src/Command/ChoosePaymentMethod.php
- src/Command/ChooseShippingMethod.php
- src/Command/CompleteOrder.php
- src/Command/DropCart.php
- src/Command/GenerateResetPasswordToken.php
- src/Command/GenerateVerificationToken.php
- src/Command/PickupCart.php
- src/Command/PutOptionBasedConfigurableItemToCart.php
- src/Command/PutSimpleItemToCart.php
- src/Command/PutVariantBasedConfigurableItemToCart.php
- src/Command/RegisterCustomer.php
- src/Command/RemoveAddress.php
- src/Command/RemoveCoupon.php
- src/Command/RemoveItemFromCart.php
- src/Command/SetDefaultAddress.php
- src/Validator/ValidPromotionCouponCodeValidator.php
> Replaced asserts with type hints

- composer.json
Missing bundles resulted in failing tests (run locally). The problem was not detected on Travis CI, as in build we [require the whole symfony/symfony](https://github.com/Sylius/ShopApiPlugin/blob/master/.travis.yml#L39) with a specific version. I suppose we should use a [require-symfony-version](https://github.com/Sylius/Sylius-Standard/blob/master/bin/require-symfony-version) script, if we still want to support both Symfony 3.4 and 4.1
> Require missing bundles in dev

- spec/Normalizer/RequestCartTokenNormalizerSpec.php
- src/Controller/Cart/PutItemToCartAction.php
- src/Controller/Cart/PutItemsToCartAction.php
- src/Normalizer/RequestCartTokenNormalizer.php
- src/Normalizer/RequestCartTokenNormalizerInterface.php
- src/Resources/config/routing/cart.yml
- src/Resources/config/services.xml
- src/Resources/config/services/actions/cart.xml
- tests/Controller/CartPutItemToCartApiTest.php
- tests/Controller/CartPutItemsToCartApiTest.php
- tests/Responses/Expected/cart/add_multiple_products_to_new_cart_response.json
- tests/Responses/Expected/cart/add_simple_product_to_new_cart_response.json
🌵 Since https://github.com/Sylius/ShopApiPlugin/pull/342 is still in a PR state and picking a new cart requires channel, one BC break needed to be implemented in `PutItemsToCartAction` (line 75). 
We can merge this PR and wait for https://github.com/Sylius/ShopApiPlugin/pull/342 to be merged and then fix it or firstly wait for https://github.com/Sylius/ShopApiPlugin/pull/342 to be merged and then rebase - as a result channel will be present in all URLs. 🌵
> Add item to cart should pick up a new cart if cart token is not passed

- doc/swagger.yml
- spec/Factory/PlacedOrderViewFactorySpec.php
- spec/ViewRepository/PlacedOrderViewRepositorySpec.php
- src/Controller/Order/ShowOrderDetailsAction.php
- src/Factory/PlacedOrderViewFactory.php
- src/Factory/PlacedOrderViewFactoryInterface.php
- src/Resources/config/routing/order.yml
- src/View/PlacedOrderView.php
- src/ViewRepository/PlacedOrderViewRepository.php
- src/ViewRepository/PlacedOrderViewRepositoryInterface.php
- tests/Controller/OrderShowApiTest.php
- tests/DataFixtures/ORM/order.yml
- tests/Responses/Expected/order/order_details_response.json
- tests/Responses/Expected/order/order_not_found_response.json
- tests/Responses/Expected/order/orders_list_response.json
This is a re-do of #347 
It is basically the same commit, but instead of allowing getting an order with ID or tokenValue, this time I switched to only use the tokenValue.
I think it is not good practice to expose the ID of an order, which is not obtainable by using the API in any way. Using the token only should be the way to go, because the token should already be present in all clients using the API and is also obtainable through picking up a cart.
> Re-done get order by tokenValue instead of ID

- src/Controller/AddressBook/RemoveAddressAction.php
- src/Controller/AddressBook/SetDefaultAddressAction.php
- src/Request/RemoveAddressRequest.php
- src/Request/SetDefaultAddressRequest.php
These 2 `*Request`s didn't have `getCommand()` method due to some validation purposes. I think it can be done this way and it would be also easier to abstract commands from requests creation in the nearest future :)
> Unify request command objects

- src/Request/VerifyAccountRequest.php
- src/Resources/config/routing/register.yml
- tests/Controller/CustomerVerifyApiTest.php
- tests/Request/VerifyAccountRequestTest.php
In order to complete the activation of new registered users I propose to change the method of `sylius_shop_api_user_verification` route to [GET] so we are able to access the activation url sent in ShopApiPlugin:Email:verification.html.twig template, when a user registers through shop api.
> Fixed shop api /verify-account route

- composer.json
Fixes error when running tests/Application/bin/console
In getSecurityCheckerCommandService.php line 9:
Attempted to load class "SecurityCheckerCommand" from namespace "SensioLabs\Security\Command".  
Did you forget a "use" statement for another namespace?
> Add security checker as dev dependency

- doc/swagger.yml
- src/Controller/Customer/LoggedInCustomerDetailsAction.php
- tests/Responses/Expected/customer/logged_in_customer_details_response.json
In order to be able to load all user details through shopApi I suggest to change the response of `sylius_shop_api_me`, adding the missing customer attributes:  `birthday`, `gender`, `phoneNumber` and `subscribedToNewsletter`
Having this, we can get and edit all customer attributes and that will be useful if you want to use Sylius as headless system, e.g.
> Add missing customer attributes to sylius_shop_api_me

- UPGRADE.md
- src/Resources/config/routing/address_book.yml
- src/Resources/config/routing/customer.yml
- src/Resources/config/routing/order.yml
All other routes of the ShopApiPlugin start with `sylius_shop_api`. Some of the routes don't follow this pattern:
:rotating_light: BC BREAK.
> Unified route names again

- spec/Handler/Cart/AddressOrderHandlerSpec.php
- src/Handler/Cart/AddressOrderHandler.php
- tests/Controller/Checkout/CheckoutAddressApiTest.php
**Before:** Addressing an order would always create two new addresses, even when we just want to change the address of an order, which fills the database with a lot of unused addresses.
**After:** The order addressing handler looks for existing addresses on the order and updates them if possible.
> Fixed order addressing filling the database with garbage

- doc/swagger.yml
The body parameter is always called content on all endpoints.
> Change parameter name to make it consistent with reset password

- doc/swagger.yml
The Sylius documentation is now available at `docs.sylius.com`.
> Fixed sylius doc url

- spec/Command/Cart/AddCouponSpec.php
- spec/Command/Cart/AddressOrderSpec.php
- spec/Command/Cart/ChangeItemQuantitySpec.php
- spec/Command/Cart/ChoosePaymentMethodSpec.php
- spec/Command/Cart/ChooseShippingMethodSpec.php
- spec/Command/Cart/CompleteOrderSpec.php
- spec/Command/Cart/DropCartSpec.php
- spec/Command/Cart/PickupCartSpec.php
- spec/Command/Cart/PutOptionBasedConfigurableItemToCartSpec.php
- spec/Command/Cart/PutSimpleItemToCartSpec.php
- spec/Command/Cart/PutVariantBasedConfigurableItemToCartSpec.php
TypeError tests don't provide any value, we are just testing that PHP itself is working correctly
> [Maintanance] Remove redundant specs

- src/ViewRepository/Product/ProductDetailsViewRepository.php
I was wondering why querying an existing product results into a channel not found error.
(Could be possible that there will be some test failures, I will fix them soon).
> fix product not assigned to channel error message

- tests/Controller/AddressBook/AddressBookCreateAddressApiTest.php
- tests/Controller/AddressBook/AddressBookUpdateAddressApiTest.php
- tests/Controller/Cart/CartAddCouponShopApiTest.php
- tests/Controller/Cart/CartChangeItemQuantityApiTest.php
- tests/Controller/Cart/CartPutItemToCartApiTest.php
- tests/Controller/Cart/CartPutItemsToCartApiTest.php
- tests/Controller/Cart/CartSummarizeApiTest.php
- tests/Controller/Checkout/CheckoutAddressApiTest.php
- tests/Controller/Checkout/CheckoutChoosePaymentMethodApiTest.php
- tests/Controller/Checkout/CheckoutChooseShippingMethodApiTest.php
- tests/Controller/Checkout/CheckoutCompleteOrderApiTest.php
- tests/Controller/Checkout/CheckoutSummarizeApiTest.php
- tests/Controller/Customer/CustomerLoginApiTest.php
- tests/Controller/Customer/CustomerRegisterApiTest.php
- tests/Controller/Customer/CustomerResendVerificationTokenApiTest.php
- tests/Controller/Customer/CustomerResetPasswordApiTest.php
- tests/Controller/Customer/CustomerUpdateCustomerApiTest.php
- tests/Controller/Customer/CustomerVerifyApiTest.php
- tests/Controller/Customer/LoggedInCustomerDetailsActionTest.php
- tests/Controller/Product/ProductAddReviewByCodeApiTest.php
- tests/Controller/Product/ProductAddReviewBySlugApiTest.php
- tests/Controller/Utils/ShopUserLoginTrait.php
Quick clean up, EOT is just sample identifier, therefor JSON could make much more sense here :)
> [Maintenance] EOT to JSON rename

- README.md
- composer.json
- doc/swagger.yml
- src/EventListener/CartBlamerListener.php
- src/EventListener/UserCartRecalculationListener.php
- src/Resources/config/routing.yml
- src/Resources/config/services.xml
- tests/Application/config/packages/security.yaml
- tests/Application/config/routes.yaml
- tests/Controller/Cart/CartPickupApiTest.php
- tests/Controller/Cart/CartPutItemToCartApiTest.php
- tests/Controller/Utils/ShopUserLoginTrait.php
- tests/DataFixtures/ORM/customer.yml
- tests/DataFixtures/ORM/promotion.yml
- tests/Responses/Expected/cart/recalculated_cart_after_log_in.json
> [Cart] Recalculate customer cart when log in

- doc/swagger.yml
- src/Controller/Customer/LoggedInCustomerDetailsAction.php
- src/Controller/Customer/UpdateCustomerAction.php
- tests/Controller/Customer/LoggedInCustomerDetailsActionTest.php
- tests/Controller/Customer/UpdateCustomerApiTest.php
The `LoggedInCustomerDetailsAction` and the `UpdateCustomerAction` now return an unauthorized response instead of throwing `TokenNotFoundException` if the user is not logged in.
> Returning 401 on customer details/update actions when not logged in

- doc/swagger.yml
- spec/Handler/Cart/PickupCartHandlerSpec.php
The https://app.swaggerhub.com/apis/Sylius/sylius-shop-api/1.0.0 is not up2date and the exist swagger.yml in doc/swagger.yml has same errors in it when copy it to https://editor.swagger.io/
> Fix errors in swagger file

- doc/swagger.yml
- src/EventListener/CartBlamerListener.php
- tests/Controller/Customer/LoginApiTest.php
Carts which are not created over the ShopApi have no tokenValue so if you try to login it will accidently try to assign a Cart which is not the one of the current value.
So a cart should only tried to be loaded when the $token is given to the api.
> Fix CartBlamerListener without token

- spec/Command/Customer/UpdateCustomerSpec.php
- spec/Handler/Customer/UpdateCustomerHandlerSpec.php
- src/Command/Customer/UpdateCustomer.php
- src/Handler/Customer/UpdateCustomerHandler.php
- src/Request/Customer/UpdateCustomerRequest.php
- tests/Request/UpdateCustomerRequestTest.php
Fixes #544 
Fixing the customer birthday
> Fixing the customer birthday

- doc/swagger.yml
- spec/Checker/ProductInCartChannelCheckerSpec.php
- spec/Handler/Cart/PutOptionBasedConfigurableItemToCartHandlerSpec.php
- spec/Handler/Cart/PutSimpleItemToCartHandlerSpec.php
- spec/Handler/Cart/PutVariantBasedConfigurableItemToCartHandlerSpec.php
- spec/Validator/Product/ProductInCartChannelValidatorSpec.php
- src/Checker/ProductInCartChannelChecker.php
- src/Checker/ProductInCartChannelCheckerInterface.php
- src/Handler/Cart/PutOptionBasedConfigurableItemToCartHandler.php
- src/Handler/Cart/PutSimpleItemToCartHandler.php
- src/Handler/Cart/PutVariantBasedConfigurableItemToCartHandler.php
- src/Request/Cart/PutOptionBasedConfigurableItemToCartRequest.php
- src/Request/Cart/PutSimpleItemToCartRequest.php
- src/Request/Cart/PutVariantBasedConfigurableItemToCartRequest.php
- src/Resources/config/services.xml
- src/Resources/config/services/checker.xml
- src/Resources/config/services/checker/channel.xml
- src/Resources/config/services/handler/cart.xml
- src/Resources/config/services/validators/product.xml
- src/Resources/config/validation/cart/PutOptionBasedConfigutableItemToCartRequest.xml
- src/Resources/config/validation/cart/PutSimpleItemToCartRequest.xml
- src/Resources/config/validation/cart/PutVariantBasedConfigutableItemToCartRequest.xml
- src/Validator/Constraints/ProductInCartChannel.php
- src/Validator/Product/ProductInCartChannelValidator.php
- tests/Controller/Cart/PutItemToCartApiTest.php
- tests/DataFixtures/ORM/channel.yml
- tests/DataFixtures/ORM/shop.yml
- tests/Responses/Expected/cart/product_not_in_cart_channel.json
Fixes #59 
Currently you can add any product to any cart. After this pull request the product needs to be available in the cart's channel. So that if a product is in channel A and the cart is picked up in channel B then the product-add endpoint will now throw an error (500).
The problem is that the Validation would need to take two properties of the request into consideration: the current cart token, the product code. Which means that it has to be a "Class Constraint" and needs to access properties of the request object. This is currently not possible as the current request objects don't have getter and the properties are private. So there is no way of validating them. Therefore this pull request only adds an assertion that it is true. (validation may follow if it will be possible to do …
> Addding assertions for product in current channel

- src/Handler/Customer/RegisterCustomerHandler.php
- src/Provider/ShopUserAwareCustomerProvider.php
- src/Resources/config/services/handler/customer.xml
- tests/Controller/Customer/RegisterApiTest.php
Closes #533
This would handle the registration process like Standard Sylius that a Customer is set to the User if the E-Mail Address exist as a customer. Currently you are not able to register if you did an anonymous order over the shop api.
> Handle registration for exist customer

- composer.json
- src/Mailer/Emails.php
In the most recent version of phpstan's assert implementation the "implements" assertion has been added this howerver does not work with the current usage. I already made a pull request to fix it but other than that we need to exclude this version until it's fixed.
> Fixing dependencies

- src/Command/Customer/UpdateCustomer.php
- tests/Controller/Customer/LoggedInCustomerDetailsActionTest.php
- tests/Controller/Customer/UpdateCustomerApiTest.php
- tests/DataFixtures/ORM/customer.yml
- tests/Responses/Expected/address_book/add_address_response.json
- tests/Responses/Expected/address_book/show_address_book_response.json
- tests/Responses/Expected/customer/logged_in_customer_details_response.json
- tests/Responses/Expected/customer/update_customer.json
This PR fixes/changes the folloing things:
* (DX) In the tests the customer details test the login request is replaced with the trait that does the request
* (DX) Removed credentials from "customer is not logged in" test.
* (DX) Extracted requesting the endpoint into a function (and now with globally defined `CONTENT_TYPE_HEADER`)
* Fixing type bug. If you instanciate the `UpdateCustomer` with null for `subscribedToNewsletter` then the getter for it will crash as null is not part of the return type.
> Extending customer details tests

- composer.json
This pull request aligns the constraint of the Symfony messenger component required by ShopApiPlugin with the other Symfony constraints from Sylius main package. (And therefor allows to upgrade to v4.4 of Symfony's messenger component.)
> Loosen dep constraint for Symfony messenger component

- doc/swagger.yml
- spec/Handler/Cart/PickupCartHandlerSpec.php
- src/Resources/config/routing/customer.yml
- tests/Controller/Customer/ChangePasswordApiTest.php
Closes #28
This PR adds a `sylius_shop_api_change_password` route with the path `/me/change-password`.
The route allows to change the password of the user that is currently logged in.
The PR does not implement any new action, but rather uses the existing `changePasswordAction` of the `UserController` of Sylius. This is the same strategy that is already used for the `sylius_shop_api_password_reset` route.
> Add route for changing password of current user

- src/Resources/config/validation/customer/UpdateCustomerRequest.xml
- src/Resources/translations/validators.en.yml
- tests/Controller/Customer/UpdateCustomerApiTest.php
- tests/Responses/Expected/customer/validation_empty_data.json
- tests/Responses/Expected/customer/validation_gender_not_valid_response.json
Add Validation on Gender field [Update Customer Request]
Gender Filed will only accept these letters ['u', 'm', 'f'].
related issue #614
> Add Validation on Customer Gender

- README.md
Since this plugin is stable, it should define a release cycle for both bugfixes and security fixes.
> Define release cycle for Shop API

- doc/swagger.yml
- spec/Command/Order/UpdatePaymentMethodSpec.php
- spec/Factory/Order/PlacedOrderViewFactorySpec.php
- spec/Handler/Order/UpdatePaymentMethodHandlerSpec.php
- spec/Validator/Order/OrderExistsValidatorSpec.php
- src/Command/Order/UpdatePaymentMethod.php
- src/Controller/Order/UpdatePaymentMethodAction.php
- src/Factory/Order/PlacedOrderViewFactory.php
- src/Handler/Order/UpdatePaymentMethodHandler.php
- src/Request/Order/UpdatePaymentMethodRequest.php
- src/Resources/config/routing/order.yml
- src/Resources/config/services/actions/order.xml
- src/Resources/config/services/handler/order.xml
- src/Resources/config/services/validators/order.xml
- src/Resources/config/validation/order/UpdatePaymentMethodRequest.xml
- src/Validator/Constraints/OrderExists.php
- src/Validator/Constraints/PaymentNotPaid.php
- src/Validator/Order/OrderExistsValidator.php
- src/Validator/Order/PaymentNotPaidValidator.php
- src/View/Order/PlacedOrderView.php
- tests/Controller/Order/OrderUpdatePaymentMethodApiTest.php
- tests/Responses/Expected/order/order_details_response.json
- tests/Responses/Expected/order/order_details_response_guest.json
- tests/Responses/Expected/order/orders_list_response.json
Hi,
We have implemented two new actions to handle payment state on placed orders:
1. Get available payment methods: Same as /{channelCode}/checkout/{token}/payment but on order endpoint.
2. Update payment method on unpaid placed orders to implement the same behavior as in ShopBundle to allow a customer to change the payment method while order is unpaid.
1 is just reusing the same action from checkout, not sure if I should reimplement this as a different action.
2 adds validation as I've seen on other controllers, is this the preferred approach?
Tests are failing, there's something weird I couldn't figure out on loading the fixtures. I bet I'm doing something wrong. Am I missing something obvious there?
I've also added a new field to placedorder view: paymentState.
David.
> Implemented order available payment methods and order update payment

- doc/Cookbook.md
This detail would have helped me if it were here
> Add documentation details on how to extends views

- .travis.yml
After the update of the documentation parser the executable is renamed.
> Fixing the documentation parser

- src/Command/Cart/PickupCart.php
- src/Command/LocaleAwareCommandInterface.php
- src/CommandProvider/ChannelBasedCommandProvider.php
- src/Handler/Cart/PickupCartHandler.php
- src/Resources/config/services/command_providers/cart.xml
- tests/Controller/Cart/PickupApiTest.php
- tests/Responses/Expected/cart/empty_response_de_DE.json
Currently when picking up a new cart, the default channel locale is always used.
This PR fixes this by enabling the use of an optional ?locale URL parameter to customize the cart's locale.
> Allow customizing picked up cart's locale

- README.md
Adding a release table for this plugin to denote the support time of the individual versions.
> Adding a release table

- README.md
Replace sylius_api.security.regex with `sylius_shop_api.security.regex`
> Documentation: fix wrong parameter name

- doc/swagger.yml
- spec/Factory/Cart/CartItemViewFactorySpec.php
- src/Factory/Cart/CartItemViewFactory.php
- src/View/ItemView.php
- tests/Responses/Expected/cart/add_multiple_products_to_cart_response.json
- tests/Responses/Expected/cart/add_multiple_products_to_new_cart_response.json
- tests/Responses/Expected/cart/add_product_variant_based_on_options_multiple_times_to_cart_response.json
- tests/Responses/Expected/cart/add_product_variant_based_on_options_to_cart_response.json
- tests/Responses/Expected/cart/add_product_variant_multiple_times_to_cart_response.json
- tests/Responses/Expected/cart/add_product_variant_to_cart_response.json
- tests/Responses/Expected/cart/add_simple_product_multiple_times_to_cart_response.json
- tests/Responses/Expected/cart/add_simple_product_to_cart_response.json
- tests/Responses/Expected/cart/add_simple_product_to_new_cart_response.json
- tests/Responses/Expected/cart/cart_with_coupon_based_promotion_applied_response.json
- tests/Responses/Expected/cart/filled_cart_with_product_variant_summary_response.json
- tests/Responses/Expected/cart/filled_cart_with_simple_product_summary_response.json
- tests/Responses/Expected/cart/german_filled_cart_with_product_variant_summary_response.json
- tests/Responses/Expected/cart/german_filled_cart_with_simple_product_summary_response.json
- tests/Responses/Expected/cart/recalculated_cart_after_log_in.json
- tests/Responses/Expected/cart/reprocessed_cart_after_deleting_an_item.json
- tests/Responses/Expected/checkout/cart_addressed_response.json
- tests/Responses/Expected/checkout/cart_addressed_with_different_shipping_and_billing_address_response.json
- tests/Responses/Expected/checkout/cart_addressed_with_province_codes_response.json
- tests/Responses/Expected/checkout/cart_with_chosen_payment_response.json
- tests/Responses/Expected/checkout/cart_with_chosen_shipment_response.json
- tests/Responses/Expected/checkout/cart_with_chosen_shipment_with_per_item_rate_response.json
- tests/Responses/Expected/checkout/modified_cart_with_chosen_shipment_with_per_item_rate_response.json
- tests/Responses/Expected/order/order_details_response.json
- tests/Responses/Expected/order/order_details_response_guest.json
- tests/Responses/Expected/order/orders_list_response.json
This partially solves #638 but without the BC break.
> Adding a subtotal property to the cart endpoint

- spec/Validator/Address/AddressExistsValidatorSpec.php
- src/Validator/Address/AddressExistsValidator.php
Hi there, 
I've got an error during validation of address existence in case when it does not belong to any customer:
see `AddressExistsValidator`
```php
if ($address->getCustomer()->getEmail() !== $user->getEmail()) {
return $this->context->addViolation($constraint->message);
}
```
> [Address] Handle adress exists validation in case when address does not belong to any customer

- .github/workflows/build.yml
- composer.json
- phpstan.neon
- tests/Application/config/bundles.php
- tests/Application/config/packages/_sylius.yaml
- tests/Application/config/packages/security.yaml
- tests/Application/config/routes/sylius_admin_api.yaml
- tests/Controller/Customer/LoginApiTest.php
- tests/Controller/Customer/RegisterApiTest.php
- tests/Controller/Customer/RequestPasswordResettingApiTest.php
- tests/Controller/Customer/ResendVerificationTokenApiTest.php
- tests/Controller/Customer/ResetPasswordApiTest.php
- tests/Controller/Customer/VerifyApiTest.php
- tests/Controller/Utils/PurgeSpooledMessagesTrait.php
- tests/Responses/Expected/address_book/add_address_response.json
- tests/Responses/Expected/address_book/show_address_book_response.json
> [Maintenance] Support for Sylius 1.8 dropped, Sylius 1.10 added,  Symfony 5.3 added, PHP 8.0 added

- composer.json
With the current composer.json constraints regarding the Symfony packages we only are allowed to install version `5.2.0` of the packages. This PR fixes this and allows `^5.2` to be installed.
> Fix Symfony package constraints

- src/Factory/ImageViewFactory.php
Fixes #695 
Liip Imagine cannot handle svg files so we keep original svg path
> fix: do not try to filter svg images

- README.md
- Update README file link to avoid 404 since the link does not work anymore with the external bundle
> Update README file link to auth bundle
