- tests/Controller/CartShopAPITest.php
I would be more understandable if we rename this class
> [RFC] Rename CartViewTest to CartShopAPITest

- README.md
> [README] Make test section great

- composer.json
- phpspec.yml.dist
- spec/Builder/ImageViewBuilderSpec.php
- src/Builder/ImageViewBuilder.php
- src/Builder/ImageViewBuilderInterface.php
- src/Controller/ProductController.php
- src/Controller/TaxonController.php
- src/Resources/config/routing.yml
- src/Resources/config/routing/taxon.yml
- src/Resources/config/services.xml
- src/View/TaxonView.php
- tests/Controller/ProductShopAPITest.php
- tests/Controller/TaxonShopAPITest.php
- tests/DataFixtures/ORM/shop.yml
- tests/Responses/Expected/product/limited_product_list_page.json
- tests/Responses/Expected/product/product_list_page.json
- tests/Responses/Expected/taxon/all_taxons_response.json
- tests/Responses/Expected/taxon/one_of_taxons_response.json
> [Design] Taxons design

- src/Resources/config/routing.yml
- src/Resources/config/routing/cart.yml
- src/Resources/config/routing/product.yml
- src/Resources/config/routing/register.yml
- src/Resources/config/routing/taxon.yml
- tests/Controller/CustomerShopApiTest.php
Closes #7 
This endpoint returns an object, because of usage of ResourceController. But later, when we will move to Command Bus pattern it will be refactored anyway. 
Based on #60
> [User] Register a new customer

- src/View/AddressView.php
- src/View/PageLinksView.php
- src/View/PageView.php
- src/View/TotalsView.php
- tests/Controller/CartShopApiTest.php
- tests/Controller/ProductShopApiTest.php
- tests/Controller/TaxonShopApiTest.php
- tests/Responses/Expected/cart/german_filled_cart_with_simple_product_summary_response.json
> [Maintenance] Minor fixes

- spec/Factory/ImageViewFactorySpec.php
- src/Controller/CartController.php
- src/Controller/ProductController.php
- src/Controller/TaxonController.php
- src/Factory/ImageViewFactory.php
- src/Factory/ImageViewFactoryInterface.php
- src/Resources/config/services.xml
These classes are more factories rather than builders.
> [Maintenance] Rename builders to factories

- spec/Factory/TaxonViewFactorySpec.php
- src/Controller/TaxonController.php
- src/Factory/TaxonViewFactory.php
- src/Factory/TaxonViewFactoryInterface.php
- src/Resources/config/routing/taxon.yml
- src/Resources/config/services.xml
- src/Resources/config/services/controller.xml
During work on #80, I've decided to extract some of the common logic.
> [Taxon] Refactor Taxon controller and extract factory

- spec/Factory/ProductViewFactorySpec.php
- src/Factory/ProductViewFactory.php
- tests/Responses/Expected/cart/filled_cart_with_product_variant_summary_response.json
- tests/Responses/Expected/cart/filled_cart_with_simple_product_summary_response.json
- tests/Responses/Expected/cart/german_filled_cart_with_product_variant_summary_response.json
- tests/Responses/Expected/cart/german_filled_cart_with_simple_product_summary_response.json
- tests/Responses/Expected/product/german_product_with_options_details_page.json
- tests/Responses/Expected/product/german_simple_product_details_page.json
- tests/Responses/Expected/product/limited_product_list_page.json
- tests/Responses/Expected/product/product_list_page.json
- tests/Responses/Expected/product/product_with_options_details_page.json
- tests/Responses/Expected/product/product_with_variant_details_page.json
- tests/Responses/Expected/product/simple_product_details_page.json
> [Taxonomy] [Product] Add taxon code to product response

- tests/Controller/CheckoutSummarizeShopApiTest.php
> [Fix] Remove data from get

- spec/Factory/CartViewFactorySpec.php
- spec/Factory/ShipmentViewFactorySpec.php
- spec/Factory/ShippingMethodViewFactorySpec.php
- src/Controller/Checkout/ChooseShippingMethodAction.php
- src/Controller/Checkout/ShowAvailableShippingMethodsAction.php
- src/Controller/Checkout/SummarizeAction.php
- src/Factory/CartViewFactory.php
- src/Factory/ShipmentViewFactory.php
- src/Factory/ShipmentViewFactoryInterface.php
- src/Factory/ShippingMethodViewFactory.php
- src/Factory/ShippingMethodViewFactoryInterface.php
- src/Resources/config/services.xml
- src/Resources/config/services/controller.xml
- src/View/ShipmentView.php
- src/View/ShippingMethodView.php
- tests/Controller/CheckoutSummarizeShopApiTest.php
- tests/Responses/Expected/checkout/cart_with_chosen_shipment_response.json
- tests/Responses/Expected/checkout/get_available_shipping_methods.json
> [Checkout] Presenting cart with shipping

- spec/Factory/CartViewFactorySpec.php
- spec/Factory/PaymentMethodViewFactorySpec.php
- spec/Factory/ShipmentViewFactorySpec.php
- spec/Factory/ShippingMethodViewFactorySpec.php
- src/Controller/Checkout/ChooseShippingMethodAction.php
- src/Controller/Checkout/ShowAvailablePaymentMethodsAction.php
- src/Controller/Checkout/ShowAvailableShippingMethodsAction.php
- src/Controller/Checkout/SummarizeAction.php
- src/Factory/CartViewFactory.php
- src/Factory/PaymentMethodViewFactory.php
- src/Factory/PaymentMethodViewFactoryInterface.php
- src/Factory/ShipmentViewFactory.php
- src/Factory/ShipmentViewFactoryInterface.php
- src/Factory/ShippingMethodViewFactory.php
- src/Factory/ShippingMethodViewFactoryInterface.php
- src/Resources/config/routing/checkout.yml
- src/Resources/config/services.xml
- src/Resources/config/services/controller.xml
- src/View/PaymentMethodView.php
- src/View/ShipmentView.php
- src/View/ShippingMethodView.php
- tests/Controller/CheckoutShowAvailablePaymentMethodsShopApiTest.php
- tests/Controller/CheckoutSummarizeShopApiTest.php
- tests/DataFixtures/ORM/payment.yml
- tests/Responses/Expected/checkout/cart_with_chosen_shipment_response.json
- tests/Responses/Expected/checkout/get_available_payment_methods.json
- tests/Responses/Expected/checkout/get_available_shipping_methods.json
It is compound PR from #89 and #83 which were open to different branches in order to reduce the scope of code to review. As they are 1:1 equal to the merged ones, I will merge them as soon as they turn green.
> Rebased payments

- tests/Controller/CheckoutChooseShippingMethodApiTest.php
It doesn't make any sense. I will deal with validation in separate PR.
> Remove unneded test

- spec/Command/ChoosePaymentMethodSpec.php
- spec/Factory/CartViewFactorySpec.php
- spec/Factory/PaymentViewFactorySpec.php
- spec/Handler/ChoosePaymentMethodHandlerSpec.php
- src/Command/ChoosePaymentMethod.php
- src/Controller/Checkout/ChoosePaymentMethodAction.php
- src/Factory/CartViewFactory.php
- src/Factory/PaymentViewFactory.php
- src/Factory/PaymentViewFactoryInterface.php
- src/Factory/ShipmentViewFactory.php
- src/Handler/ChoosePaymentMethodHandler.php
- src/Resources/config/routing/checkout.yml
- src/Resources/config/services.xml
- src/Resources/config/services/controller.xml
- src/View/PaymentView.php
- tests/Controller/CheckoutChoosePaymentMethodApiTest.php
- tests/Controller/CheckoutSummarizeShopApiTest.php
- tests/Responses/Expected/checkout/cart_with_chosen_payment_response.json
> [Checkout] Choose checkout payment

- src/Controller/Cart/SummarizeAction.php
- src/Controller/CartController.php
- src/Resources/config/routing/cart.yml
- src/Resources/config/routing/checkout.yml
- src/Resources/config/services/actions/cart.xml
- src/Resources/config/services/actions/checkout.xml
- src/Resources/config/services/controllers.xml
- tests/Controller/CartApiTest.php
- tests/Controller/CartSummarizeApiTest.php
Checkout summary and cart summary are the same at the moment.
> [Cart] Extract common summary action

- src/Controller/Cart/PickupAction.php
- src/Controller/Cart/SummarizeAction.php
- src/Controller/CartController.php
- src/Resources/config/routing/cart.yml
- src/Resources/config/routing/checkout.yml
- src/Resources/config/services/actions/cart.xml
- src/Resources/config/services/actions/checkout.xml
- src/Resources/config/services/controllers.xml
- tests/Controller/CartApiTest.php
- tests/Controller/CartPickupApiTest.php
- tests/Controller/CartSummarizeApiTest.php
> [Cart] Extract cart pickup action

- spec/Factory/ImageViewFactorySpec.php
- src/Factory/ImageViewFactory.php
- src/Resources/config/serializer/ImageView.yml
- src/View/ImageView.php
- tests/Responses/Expected/cart/filled_cart_with_product_variant_summary_response.json
- tests/Responses/Expected/cart/filled_cart_with_simple_product_summary_response.json
- tests/Responses/Expected/cart/german_filled_cart_with_simple_product_summary_response.json
- tests/Responses/Expected/checkout/cart_addressed_response.json
- tests/Responses/Expected/checkout/cart_addressed_with_different_shipping_and_billing_address_response.json
- tests/Responses/Expected/checkout/cart_with_chosen_payment_response.json
- tests/Responses/Expected/checkout/cart_with_chosen_shipment_response.json
- tests/Responses/Expected/product/german_simple_product_details_page.json
- tests/Responses/Expected/product/limited_product_list_page.json
- tests/Responses/Expected/product/product_list_page.json
- tests/Responses/Expected/product/product_with_variant_details_page.json
- tests/Responses/Expected/product/simple_product_details_page.json
- tests/Responses/Expected/taxon/all_taxons_response.json
- tests/Responses/Expected/taxon/german_all_taxons_response.json
- tests/Responses/Expected/taxon/german_one_of_taxons_response.json
- tests/Responses/Expected/taxon/one_of_taxons_response.json
> [Image] Show path instead of url

- spec/Factory/TotalViewFactorySpec.php
- src/Factory/TotalViewFactory.php
- src/View/TotalsView.php
- tests/Responses/Expected/cart/empty_response.json
- tests/Responses/Expected/cart/filled_cart_with_product_variant_summary_response.json
- tests/Responses/Expected/cart/filled_cart_with_simple_product_summary_response.json
- tests/Responses/Expected/cart/german_filled_cart_with_product_variant_summary_response.json
- tests/Responses/Expected/cart/german_filled_cart_with_simple_product_summary_response.json
- tests/Responses/Expected/checkout/cart_addressed_response.json
- tests/Responses/Expected/checkout/cart_addressed_with_different_shipping_and_billing_address_response.json
- tests/Responses/Expected/checkout/cart_with_chosen_payment_response.json
- tests/Responses/Expected/checkout/cart_with_chosen_shipment_response.json
> [Cart] Add grand total

- tests/Responses/Expected/product/german_product_with_options_details_page.json
- tests/Responses/Expected/product/product_with_options_details_page.json
Master should be broken at the moment.
> [HOTFIX] Fix association view

- .travis.yml
- README.md
- src/Resources/config/services.xml
- tests/Application/app/AppKernel.php
- tests/Application/app/config/config.yml
- tests/Application/app/config/routing.yml
- tests/Responses/Expected/product/german_product_with_options_details_page.json
- tests/Responses/Expected/product/product_with_options_details_page.json
> [Shop] Bring back regular SyliusShop

- spec/Factory/CartItemViewFactorySpec.php
- spec/Factory/DetailedProductViewFactorySpec.php
- spec/Factory/ProductViewFactorySpec.php
- src/Controller/Product/ShowProductCatalogAction.php
- src/Controller/Product/ShowProductDetailsAction.php
- src/Factory/CartItemViewFactory.php
- src/Factory/DetailedProductViewFactory.php
- src/Factory/ProductViewFactory.php
- src/Factory/ProductViewFactoryInterface.php
- src/Resources/config/services/actions/product.xml
- src/Resources/config/services/factories.xml
- tests/Responses/Expected/product/product_list_page.json
> [Product] Add association to PLP

- spec/Command/AddCouponSpec.php
- spec/Handler/AddCouponHandlerSpec.php
- src/Command/AddCoupon.php
- src/Controller/Cart/AddCouponAction.php
- src/Handler/AddCouponHandler.php
- src/Resources/config/routing/cart.yml
- src/Resources/config/services/actions/cart.xml
- src/Resources/config/services/handlers.xml
- tests/Controller/CartAddCouponShopApiTest.php
- tests/Controller/CartApiTest.php
- tests/DataFixtures/ORM/coupon_based_promotion.yml
- tests/Responses/Expected/cart/cart_with_coupon_based_promotion_applied_response.json
> [Cart] Add coupon to cart

- spec/Command/CompleteOrderSpec.php
- spec/Handler/CompleteOrderHandlerSpec.php
- src/Command/CompleteOrder.php
- src/Controller/Checkout/CompleteOrderAction.php
- src/Handler/CompleteOrderHandler.php
- src/Resources/config/routing/checkout.yml
- src/Resources/config/services/actions/checkout.xml
- src/Resources/config/services/handlers.xml
- tests/Controller/CheckoutCompleteOrderApiTest.php
- tests/Responses/Expected/cart/cart_with_coupon_based_promotion_applied_response.json
> [Checkout] Complete order

- README.md
> [README] Add tactician bundle

- spec/Factory/ProductAttributeValueViewFactorySpec.php
- spec/Factory/ProductViewFactorySpec.php
- src/Factory/DetailedProductViewFactory.php
- src/Factory/ProductAttributeValueViewFactory.php
- src/Factory/ProductAttributeValueViewFactoryInterface.php
- src/Factory/ProductViewFactory.php
- src/Resources/config/services/factories.xml
- src/View/ProductAttributeValueView.php
- tests/Controller/ShowProductDetailsApiTest.php
- tests/DataFixtures/ORM/shop.yml
- tests/Responses/Expected/cart/cart_with_coupon_based_promotion_applied_response.json
- tests/Responses/Expected/cart/filled_cart_with_simple_product_summary_response.json
- tests/Responses/Expected/cart/german_filled_cart_with_simple_product_summary_response.json
- tests/Responses/Expected/checkout/cart_addressed_response.json
- tests/Responses/Expected/checkout/cart_addressed_with_different_shipping_and_billing_address_response.json
- tests/Responses/Expected/checkout/cart_with_chosen_payment_response.json
- tests/Responses/Expected/checkout/cart_with_chosen_shipment_response.json
- tests/Responses/Expected/product/german_product_with_options_details_page.json
- tests/Responses/Expected/product/german_simple_product_details_page.json
- tests/Responses/Expected/product/product_list_page.json
- tests/Responses/Expected/product/product_with_options_details_page.json
- tests/Responses/Expected/product/simple_product_details_page.json
> [Product] Add attribute view

- spec/Factory/ProductViewFactorySpec.php
- src/Factory/ProductViewFactory.php
- src/Resources/config/services/factories.xml
- tests/Responses/Expected/cart/cart_with_coupon_based_promotion_applied_response.json
- tests/Responses/Expected/cart/filled_cart_with_product_variant_summary_response.json
- tests/Responses/Expected/cart/filled_cart_with_simple_product_summary_response.json
- tests/Responses/Expected/cart/german_filled_cart_with_product_variant_summary_response.json
- tests/Responses/Expected/cart/german_filled_cart_with_simple_product_summary_response.json
- tests/Responses/Expected/checkout/cart_addressed_response.json
- tests/Responses/Expected/checkout/cart_addressed_with_different_shipping_and_billing_address_response.json
- tests/Responses/Expected/checkout/cart_with_chosen_payment_response.json
- tests/Responses/Expected/checkout/cart_with_chosen_shipment_response.json
- tests/Responses/Expected/product/german_product_with_options_details_page.json
- tests/Responses/Expected/product/german_simple_product_details_page.json
- tests/Responses/Expected/product/limited_product_list_page.json
- tests/Responses/Expected/product/product_list_page.json
- tests/Responses/Expected/product/product_with_options_details_page.json
- tests/Responses/Expected/product/product_with_variant_details_page.json
- tests/Responses/Expected/product/simple_product_details_page.json
> [Product] Refactor taxon view

- .travis.yml
- composer.json
- spec/Factory/LimitedProductAttributeValuesViewFactorySpec.php
- spec/Factory/ProductViewFactorySpec.php
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/ShopApiExtension.php
- src/Factory/LimitedProductAttributeValuesViewFactory.php
- src/Factory/ProductAttributeValuesViewFactoryInterface.php
- src/Factory/ProductViewFactory.php
- src/Resources/config/services/factories.xml
- tests/Application/app/config/config.yml
- tests/DependencyInjection/ConfigurationTest.php
- tests/DependencyInjection/ShopApiExtensionTest.php
- tests/Responses/Expected/cart/cart_with_coupon_based_promotion_applied_response.json
- tests/Responses/Expected/cart/filled_cart_with_simple_product_summary_response.json
- tests/Responses/Expected/cart/german_filled_cart_with_simple_product_summary_response.json
- tests/Responses/Expected/checkout/cart_addressed_response.json
- tests/Responses/Expected/checkout/cart_addressed_with_different_shipping_and_billing_address_response.json
- tests/Responses/Expected/checkout/cart_with_chosen_payment_response.json
- tests/Responses/Expected/checkout/cart_with_chosen_shipment_response.json
- tests/Responses/Expected/product/german_product_with_options_details_page.json
- tests/Responses/Expected/product/german_simple_product_details_page.json
- tests/Responses/Expected/product/product_list_page.json
- tests/Responses/Expected/product/product_with_options_details_page.json
- tests/Responses/Expected/product/simple_product_details_page.json
> [Product] Serialize only specified attributes

- .travis.yml
- composer.json
- spec/Command/ChangeItemQuantitySpec.php
- spec/Handler/ChangeItemQuantityHandlerSpec.php
- spec/Validator/CartItemExistsValidatorSpec.php
- src/Command/ChangeItemQuantity.php
- src/Controller/Cart/ChangeItemQuantityAction.php
- src/Controller/CartController.php
- src/Handler/ChangeItemQuantityHandler.php
- src/Request/ChangeItemQuantityRequest.php
- src/Resources/config/routing/cart.yml
- src/Resources/config/services/actions/cart.xml
- src/Resources/config/services/handlers.xml
- src/Resources/config/services/validators.xml
- src/Resources/config/validation/ChangeItemQuantityRequest.xml
- src/Validator/CartItemExistsValidator.php
- src/Validator/Constraints/CartItemExists.php
- tests/Controller/CartApiTest.php
- tests/Controller/CartChangeItemQuantityApiTest.php
- tests/Request/ChangeItemQuantityRequestTest.php
- tests/Responses/Expected/cart/validation_cart_and_cart_item_not_exist_response.json
- tests/Responses/Expected/cart/validation_cart_item_not_exists_response.json
> [Cart] Extract and validate change item quantity action

- src/Controller/Product/ShowProductCatalogAction.php
- src/Controller/Product/ShowProductDetailsAction.php
- src/Controller/Product/ShowReviewsAction.php
- src/Resources/config/validation/ChangeItemQuantityRequest.xml
Fixes [comment](https://github.com/Sylius/SyliusShopApiPlugin/pull/150#discussion_r119853517)
> [Product] Small improvement

- spec/Command/AddReviewSpec.php
- spec/Handler/AddReviewHandlerSpec.php
- spec/Handler/CompleteOrderHandlerSpec.php
- spec/Provider/CustomerProviderSpec.php
- spec/Provider/ProductReviewerProviderSpec.php
- src/Command/AddReview.php
- src/Controller/Product/AddReviewAction.php
- src/Handler/AddReviewHandler.php
- src/Handler/CompleteOrderHandler.php
- src/Provider/CustomerProvider.php
- src/Provider/CustomerProviderInterface.php
- src/Provider/ProductReviewerProvider.php
- src/Provider/ProductReviewerProviderInterface.php
- src/Request/AddReviewRequest.php
- src/Resources/config/routing/product.yml
- src/Resources/config/services.xml
- src/Resources/config/services/actions/product.xml
- src/Resources/config/services/handlers.xml
- tests/Controller/ProductAddReviewApiTest.php
- tests/Request/AddReviewRequestTest.php
> [Product] Add review

- doc/swagger.yml
All other yaml files have 4 space indention. This PR unify swagger file with them.
> [Maintenance] Unify yaml indention

- src/View/CartSummaryView.php
- src/View/ItemView.php
- src/View/PageView.php
- src/View/PaymentView.php
- src/View/ProductVariantView.php
- src/View/ShipmentView.php
- src/View/ShippingMethodView.php
- src/View/VariantOptionView.php
Mentioned in [comment](https://github.com/Sylius/SyliusShopApiPlugin/pull/173#discussion_r125448952)
> [Enhancement] Add objects creation to view constructor

- spec/Handler/PutOptionBasedConfigurableItemToCartHandlerSpec.php
- spec/Handler/PutSimpleItemToCartHandlerSpec.php
- spec/Handler/PutVariantBasedConfigurableItemToCartHandlerSpec.php
- spec/Modifier/OrderModifierSpec.php
- src/Handler/PutOptionBasedConfigurableItemToCartHandler.php
- src/Handler/PutSimpleItemToCartHandler.php
- src/Handler/PutVariantBasedConfigurableItemToCartHandler.php
- src/Modifier/OrderModifier.php
- src/Modifier/OrderModifierInterface.php
- src/Resources/config/services.xml
- src/Resources/config/services/handlers.xml
- tests/Controller/CartPutItemToCartApiTest.php
- tests/Responses/Expected/cart/add_product_variant_based_on_options_multiple_times_to_cart_response.json
- tests/Responses/Expected/cart/add_product_variant_based_on_options_to_cart_response.json
- tests/Responses/Expected/cart/add_product_variant_multiple_times_to_cart_response.json
- tests/Responses/Expected/cart/add_product_variant_to_cart_response.json
- tests/Responses/Expected/cart/add_simple_product_multiple_times_to_cart_response.json
- added functionality of modify existing order item if adding product/variant has been added to cart before
- added some tests for new functionality
- added some missing tests for previous implementations that were not covered
> [Cart] Adding product to cart multiple times bug fix

- src/Processor/OrderShipmentProcessor.php
- src/Resources/config/services.xml
- tests/Controller/CheckoutSummarizeApiTest.php
- tests/DataFixtures/ORM/shipping.yml
- tests/Responses/Expected/checkout/cart_with_chosen_shipment_with_per_item_rate_response.json
- tests/Responses/Expected/checkout/get_available_shipping_methods.json
- tests/Responses/Expected/checkout/modified_cart_with_chosen_shipment_with_per_item_rate_response.json
Related to https://github.com/Sylius/Sylius/pull/8352.
The service overriding is just a temporary solution, until we could use the implementation proposed in mentioned PR.
> Updating shipping cost after decreasing quantity

- composer.json
- src/Resources/config/serializer/ProductVariantView.yml
> Remove applied promotions from mapping

- composer.json
- spec/EventListener/UserRegistrationListenerSpec.php
- src/Command/RegisterCustomer.php
- src/Controller/Customer/RegisterCustomerAction.php
- src/Event/CustomerRegistered.php
- src/EventListener/UserRegistrationListener.php
- src/Handler/RegisterCustomerHandler.php
- src/Request/RegisterCustomerRequest.php
- src/Resources/config/routing/register.yml
- src/Resources/config/services.xml
- src/Resources/config/services/actions/customer.xml
- src/Resources/config/services/handlers.xml
- src/Resources/config/services/validators.xml
- src/Resources/config/validation/RegisterCustomerRequest.xml
- src/Resources/translations/validators.en.yml
- src/Validator/Constraints/ShopUserDoesNotExist.php
- src/Validator/ShopUserDoesNotExistValidator.php
- tests/Controller/CustomerRegisterApiTest.php
- tests/Controller/CustomerResendVerificationTokenApiTest.php
- tests/Controller/CustomerVerifyApiTest.php
- tests/DataFixtures/ORM/channel.yml
- tests/Responses/Expected/customer/validation_registration_data_response.json
- tests/Responses/Expected/customer/validation_registration_email_taken_response.json
Changed registration API:
```diff,json
{
-  "user": {
-    "plainPassword": {
-      "first": "foobar",
-      "second": "foobar"
-    }
-  }
+  "plainPassword": "foobar",
+  "channel": "CHANNEL_CODE"
}
```
> Customer registration

- src/Command/RemoveItemFromCart.php
- src/Controller/Cart/RemoveItemFromCartAction.php
- src/Handler/RemoveItemFromCartHandler.php
- src/Request/RemoveItemFromCartRequest.php
- src/Resources/config/routing/cart.yml
- src/Resources/config/services/actions/cart.xml
- src/Resources/config/services/handlers.xml
- src/Resources/config/validation/RemoveItemFromCartRequest.xml
- tests/Controller/CartApiTest.php
- tests/Controller/CartRemoveItemFromCartApiTest.php
- tests/DataFixtures/ORM/promotion.yml
- tests/Responses/Expected/cart/cart_after_deleting_an_item.json
- tests/Responses/Expected/cart/cart_item_has_not_been_found_response.json
- tests/Responses/Expected/cart/reprocessed_cart_after_deleting_an_item.json
Adds order processing after an item is removed from the cart.
> Reimplement removing an item from the cart as a standalone action

- src/Controller/Checkout/ShowAvailableShippingMethodsAction.php
Small fix to allow the ShippingMethodViewFactory class to be overriden
> Fixed ShowAvailableShippingMethodsAction constructor argument typehinting to use interfaces

- .travis.yml
Closes #279, waiting for #293 to be merged.
> Test on Travis CI using different Symfony versions

- README.md
Fixes #298 
Ref: https://github.com/Sylius/SyliusDemo/pull/50
Testing website: http://pr-50-xigxhwq-ww4rb5tyg6lkm.eu.platform.sh/
> [README] Pre release improvements

- README.md
> [README] Mention about shop api mailing config

- composer.json
- src/View/VariantOptionView.php
>  [Maintenance] Add phpstan

- .travis.yml
- composer.json
- phpstan.neon
- src/Controller/CartController.php
- src/Controller/Customer/CustomerController.php
- src/Handler/RemoveItemFromCartHandler.php
- src/Handler/UpdateAddressBookAddressHandler.php
Added phpstan and enforced level 2.
The thing with the validators is a problem. Maybe you want to add a specific `ConstraintInterface` that defines this but other than that there is not possibility to guarantee that.
> Phpstan (level 2)

- src/Controller/Cart/PutItemToCartAction.php
- src/Controller/Cart/PutItemsToCartAction.php
- src/Controller/CartController.php
- src/Factory/ProductViewFactory.php
- src/Handler/PutOptionBasedConfigurableItemToCartHandler.php
- src/Provider/CustomerProvider.php
- src/Validator/ValidPromotionCouponCodeValidator.php
We are getting there.
@lchrusciel this one will probably conflict with the #303. Feel free to hit me up, if you merged any of them.
> PHPStan level 4

- src/Request/EstimateShippingCostRequest.php
- src/Validator/Constraints/CountryExists.php
- src/Validator/CountryExistsValidator.php
As described in the original issue.
> Cleaning up docs

- src/Provider/SupportedLocaleProvider.php
> Finalizing the Provider

- src/Resources/config/services/factories.xml
- src/Resources/config/services/factories/address_book.xml
- src/Resources/config/services/factories/cart.xml
- src/Resources/config/services/factories/checkout.xml
- src/Resources/config/services/factories/customer.xml
- src/Resources/config/services/factories/order.xml
- src/Resources/config/services/factories/product.xml
- src/Resources/config/services/factories/taxon.xml
- src/Resources/config/services/validators.xml
- src/Resources/config/services/validators/address.xml
- src/Resources/config/services/validators/cart.xml
- src/Resources/config/services/validators/customer.xml
- src/Resources/config/services/validators/product.xml
Starting to split up the service definitions. The moving of the classes will follow.
refs #326
> Splitting up the factories and the validator configs

- doc/swagger.yml
> Added documentation for the order endpoint

- doc/swagger.yml
- spec/ViewRepository/PlacedOrderViewRepositorySpec.php
- src/Controller/Order/ShowOrderDetailsAction.php
- src/Controller/Order/ShowOrdersListAction.php
- src/Factory/PlacedOrderViewFactory.php
- src/Resources/config/routing/order.yml
- src/Resources/config/services/actions/order.xml
- src/ViewRepository/PlacedOrderViewRepository.php
- src/ViewRepository/PlacedOrderViewRepositoryInterface.php
- tests/Controller/OrderShowApiTest.php
- tests/Controller/OrdersListApiTest.php
- tests/DataFixtures/ORM/order.yml
- tests/Responses/Expected/order/order_details_response.json
- tests/Responses/Expected/order/order_not_found_response.json
Based on https://github.com/Sylius/ShopApiPlugin/pull/314
> Logged in Customer placed order details endpoint

- spec/Validator/Address/AddressExistsValidatorSpec.php
- spec/Validator/Address/CountryExistsValidatorSpec.php
- spec/Validator/Cart/CartExistsValidatorSpec.php
- spec/Validator/Cart/CartItemExistsValidatorSpec.php
- spec/Validator/Cart/TokenIsNotUsedValidatorSpec.php
- spec/Validator/Cart/ValidPromotionCouponCodeValidatorSpec.php
- spec/Validator/Customer/ShopUserDoesNotExistValidatorSpec.php
- spec/Validator/Customer/ShopUserExistsValidatorSpec.php
- spec/Validator/Product/ConfigurableProductValidatorSpec.php
- spec/Validator/Product/ProductExistsValidatorSpec.php
- spec/Validator/Product/ProductVariantExistsValidatorSpec.php
- spec/Validator/Product/SimpleProductValidatorSpec.php
- src/Resources/config/services/validators/address.xml
- src/Resources/config/services/validators/cart.xml
- src/Resources/config/services/validators/customer.xml
- src/Resources/config/services/validators/product.xml
- src/Validator/Address/AddressExistsValidator.php
- src/Validator/Address/CountryExistsValidator.php
- src/Validator/Cart/CartExistsValidator.php
- src/Validator/Cart/CartItemExistsValidator.php
- src/Validator/Cart/TokenIsNotUsedValidator.php
- src/Validator/Cart/ValidPromotionCouponCodeValidator.php
- src/Validator/Customer/ShopUserDoesNotExistValidator.php
- src/Validator/Customer/ShopUserExistsValidator.php
- src/Validator/Product/ConfigurableProductValidator.php
- src/Validator/Product/ProductExistsValidator.php
- src/Validator/Product/ProductVariantExistsValidator.php
- src/Validator/Product/SimpleProductValidator.php
I have split up the validators as anticipated by the service structure.
The question is though: what about the Constraints? For now I left them where they are.
> Splitting up the validator

- spec/Http/RequestBasedLocaleProviderSpec.php
- src/Controller/Taxon/ShowTaxonDetailsAction.php
- src/Controller/Taxon/ShowTaxonTreeAction.php
- src/Http/RequestBasedLocaleProvider.php
- src/Http/RequestBasedLocaleProviderInterface.php
- src/Resources/config/services.xml
- src/Resources/config/services/actions/taxon.xml
- src/Resources/config/services/http.xml
- tests/Controller/TaxonShowDetailsApiTest.php
- tests/Controller/TaxonShowTreeApiTest.php
Based on https://github.com/Sylius/ShopApiPlugin/pull/342
> Use fallback locale from channel in taxon-related endpoints

- spec/Factory/PaymentMethodViewFactorySpec.php
- src/Factory/PaymentMethodViewFactory.php
- src/View/PaymentMethodView.php
- tests/DataFixtures/ORM/payment.yml
- tests/Responses/Expected/checkout/cart_with_chosen_payment_response.json
- tests/Responses/Expected/checkout/get_available_payment_methods.json
- tests/Responses/Expected/order/order_details_response.json
- tests/Responses/Expected/order/orders_list_response.json
To be able to show payment instructions by using Shop-API, I added the needed fields to the view and factory.
> Added payment instructions to PaymentMethodView

- doc/swagger.yml
Schema is valid now.
There's also some fixes on several object definitions to match current fields on API request/responses.
I like very much the proposed solution on https://github.com/Sylius/ShopApiPlugin/issues/251 but editing the file in one piece seems more simple.
> Fixed swagger.yml to match API

- doc/swagger.yml
Fixed AvailableShippingMethods object definition.
> Fixed show available shippings and payments endpoints.

- doc/swagger.yml
Add password-reset endpoint.
Fixes security property on order endpoints.
> Minor fixes to swagger definition.

- README.md
- UPGRADE.md
- src/DependencyInjection/Configuration.php
THIS IS A BC BREAK and needs to be documented. (How?)
> Changing the config key as suggested by pamil #190

- src/Resources/config/services/handler/cart.xml
> Fix handler's service name for address order

- doc/swagger.yml
- spec/Factory/Cart/CartViewFactorySpec.php
- src/Factory/Cart/CartViewFactory.php
- src/View/CartSummaryView.php
- tests/Responses/Expected/cart/cart_with_coupon_based_promotion_applied_response.json
Adding the applied coupon code to the cart view.
> Adding coupon code to cart view

- doc/swagger.yml
Fixes #416 
Fixing the error described in the ticket and fixed the TaxonDetails endpoint response documentation.
> Fixing the docs

- spec/Factory/Product/ProductAttributeValueViewFactorySpec.php
- src/Factory/Product/ProductAttributeValueViewFactory.php
- tests/DataFixtures/ORM/shop.yml
- tests/Responses/Expected/cart/german_filled_cart_with_simple_product_summary_response.json
- tests/Responses/Expected/product/german_product_list_page_by_code_response.json
- tests/Responses/Expected/product/german_product_list_page_by_slug_response.json
- tests/Responses/Expected/product/german_product_with_options_details_page.json
- tests/Responses/Expected/product/german_simple_product_details_page.json
> Added ProductAttributeValue serialization for select attribute types

- composer.json
- phpstan.neon
- src/Controller/Checkout/CompleteOrderAction.php
There are BC breaks between Messenger 4.2 and 4.3.
> Require Messenger ~4.3.0

- .travis.yml
- composer.json
Sylius 1.3 is supported with security fixes only.
> Add support for Sylius 1.5, remove for Sylius 1.3

- composer.json
- doc/swagger.yml
- spec/Command/AddressBook/UpdateAddressSpec.php
- spec/Handler/AddressBook/CreateAddressHandlerSpec.php
- spec/Handler/AddressBook/UpdateAddressBookAddressHandlerSpec.php
- spec/Handler/Cart/AddressOrderHandlerSpec.php
- spec/Mapper/AddressMapperSpec.php
- src/Command/AddressBook/UpdateAddress.php
- src/Handler/AddressBook/CreateAddressHandler.php
- src/Handler/AddressBook/UpdateAddressBookAddressHandler.php
- src/Handler/Cart/AddressOrderHandler.php
- src/Mapper/AddressMapper.php
- src/Mapper/AddressMapperInterface.php
- src/Model/Address.php
- src/Resources/config/services.xml
- src/Resources/config/services/handler/address_book.xml
- src/Resources/config/services/handler/cart.xml
- src/Resources/config/services/mapper.xml
- src/Resources/config/validation/address_book/AddressModelRequest.xml
- src/Resources/config/validation/checkout/AddressOrderRequest.xml
- tests/Controller/AddressBook/AddressBookCreateAddressApiTest.php
- tests/Controller/AddressBook/AddressBookUpdateAddressApiTest.php
- tests/Controller/Checkout/CheckoutAddressApiTest.php
- tests/Controller/Checkout/CheckoutShowAvailablePaymentMethodsShopApiTest.php
- tests/Controller/Checkout/CheckoutSummarizeApiTest.php
- tests/Responses/Expected/address_book/validation_create_address_book_response.json
- tests/Responses/Expected/address_book/validation_create_address_book_with_wrong_country_response.json
Currently the api has a few places where addresses are introduced into the system. In this pull request there is one service that handles it.
Closes #424
> Adding address mapper

- .travis.yml
- phpstan.neon
- src/Controller/Customer/LoggedInCustomerDetailsAction.php
- src/Controller/Customer/UpdateCustomerAction.php
- src/Factory/Product/ProductViewFactory.php
- src/Resources/config/services/actions/customer.xml
- tests/Responses/Expected/customer/logged_in_customer_details_response.json
Adding the user provider to the `CustomerDetailsAction` and adding the phpstan changes back in.
> More LoggedInUserProvider implementation and adding phpstan back in

- doc/swagger.yml
- spec/Factory/Product/ProductReviewViewFactorySpec.php
- src/Factory/Product/ProductReviewViewFactory.php
- src/View/Product/ProductReviewView.php
- tests/Responses/Expected/product/product_review_list_page_by_code_response.json
- tests/Responses/Expected/product/product_review_list_page_by_slug_response.json
> Adding created date to product review endpoint

- doc/swagger.yml
> [Docs][Order] Update docs after removing channel code from order routes

- README.md
- doc/swagger.yml
- src/Resources/config/routing.yml
- tests/Application/config/packages/security.yaml
- tests/Controller/Customer/CustomerLoginApiTest.php
- tests/Controller/Customer/LoggedInCustomerDetailsActionTest.php
- tests/Controller/Utils/ShopUserLoginTrait.php
> [Login] Unify and simplify requests

- spec/CommandProvider/ChannelBasedCommandProviderSpec.php
- spec/CommandProvider/DefaultCommandProviderSpec.php
- src/Command/Product/AddProductReviewByCode.php
- src/Command/Product/AddProductReviewBySlug.php
- src/CommandProvider/ChannelBasedCommandProvider.php
- src/CommandProvider/ChannelBasedCommandProviderInterface.php
- src/CommandProvider/CommandProviderInterface.php
- src/CommandProvider/DefaultCommandProvider.php
- src/Controller/Product/AddReviewByCodeAction.php
- src/Controller/Product/AddReviewBySlugAction.php
- src/DependencyInjection/Configuration.php
- src/Request/ChannelBasedRequestInterface.php
- src/Request/Product/AddProductReviewByCodeRequest.php
- src/Request/Product/AddProductReviewBySlugRequest.php
- src/Request/RequestInterface.php
- src/Resources/config/services/actions/product.xml
- src/Resources/config/services/command_providers/product.xml
- tests/Request/AddProductReviewByCodeRequestTest.php
- tests/Request/AddProductReviewBySlugRequestTest.php
- tests/Request/DropCartRequestTest.php
- tests/Test/TestChannelBasedCommand.php
- tests/Test/TestChannelBasedRequest.php
- tests/Test/TestCommand.php
- tests/Test/TestRequest.php
> [Product] Refactor product actions to use command providers

- .travis.yml
Switch to trusty due to Argon2i problems
> [HotFix] Try to fix Travis

- spec/CommandProvider/ChannelBasedCommandProviderSpec.php
- spec/CommandProvider/DefaultCommandProviderSpec.php
- src/CommandProvider/ChannelBasedCommandProvider.php
- src/CommandProvider/DefaultCommandProvider.php
- tests/Mocks/TestChannelBasedCommand.php
- tests/Mocks/TestChannelBasedRequest.php
- tests/Mocks/TestCommand.php
- tests/Mocks/TestRequest.php
> Fixes after review for new command providers concept

- README.md
- doc/swagger.yml
> Updating the documentation

- src/DependencyInjection/Configuration.php
- src/Resources/config/services/factories/address_book.xml
- tests/DependencyInjection/ConfigurationTest.php
> Remove unused address book view leftovers

- src/Controller/AddressBook/SetDefaultAddressAction.php
Fix for comments from https://github.com/Sylius/ShopApiPlugin/pull/496#pullrequestreview-266581887
> [AddressBook] Fixes for set default address action

- spec/Factory/Product/ProductVariantViewFactorySpec.php
This fixes the tests on master branch after #502 / #503 where merged into it.
> Fix product variant view factory original price test

- .travis.yml
- composer.json
Currently there are two places where phpstan does the checks which can be simpliefied.
> Moving the complete phpstan analysis to composer

- README.md
`sylius_shop_api_set_default_address` is a PATCH request
> Fix cors configuration and paths to config file

- src/Handler/Cart/PutVariantBasedConfigurableItemToCartHandler.php
- src/Validator/Product/ProductInCartChannelValidator.php
> Fixing the type errors

- src/Handler/Cart/PutVariantBasedConfigurableItemToCartHandler.php
- src/Resources/config/routing/register.yml
- src/Validator/Product/ProductInCartChannelValidator.php
> Adding more methods to the verify account

- spec/Validator/Product/ConfigurableProductValidatorSpec.php
- spec/Validator/Product/ProductExistsValidatorSpec.php
- spec/Validator/Product/SimpleProductValidatorSpec.php
- src/Resources/translations/validators.en.yml
- src/Validator/Constraints/ConfigurableProduct.php
- src/Validator/Constraints/ProductExists.php
- src/Validator/Constraints/SimpleProduct.php
- tests/Responses/Expected/cart/cart_and_country_does_not_exist_response.json
- tests/Responses/Expected/cart/cart_item_has_not_been_found_response.json
- tests/Responses/Expected/cart/validation_cart_and_cart_item_not_exist_response.json
- tests/Responses/Expected/cart/validation_cart_item_not_exists_response.json
- tests/Responses/Expected/cart/validation_cart_not_exists_response.json
- tests/Responses/Expected/cart/validation_product_not_configurable_response.json
- tests/Responses/Expected/cart/validation_product_not_defined_response.json
- tests/Responses/Expected/cart/validation_product_not_exists_response.json
- tests/Responses/Expected/cart/validation_product_not_simple_response.json
- tests/Responses/Expected/customer/validation_email_not_defined_response.json
- tests/Responses/Expected/customer/validation_email_not_found_response.json
- tests/Responses/Expected/customer/validation_email_not_valid_response.json
> Adding translations and unifying keys

- spec/Factory/Product/ProductAttributeValueViewFactorySpec.php
- src/Factory/Product/ProductAttributeValueViewResolver/DefaultProductAttributeValueViewResolver.php
- src/Factory/Product/ProductAttributeValueViewResolver/SelectProductAttributeValueViewResolver.php
Fixes https://github.com/Sylius/ShopApiPlugin/pull/586#discussion_r336771079 & https://github.com/Sylius/ShopApiPlugin/pull/586#pullrequestreview-304250557
> [Minor] Code cleanup

- .travis.yml
- tests/Responses/Expected/customer/bad_credentials_response.json
- tests/Responses/Expected/customer/validation_empty_data.json
- tests/Responses/Expected/order/order_details_response.json
- tests/Responses/Expected/order/orders_list_response.json
- tests/Responses/Expected/reviews/add_review_failed_rating.json
Basically fixing the build by updating PHPUnit test mockups 🙂 
#SymfonyHackday
> Update test mockups and fix the build

- composer.json
> Add missing branch alias

- CHANGELOG.md
> [CHANGELOG] Generate changelog for v1.0.0-rc.3

- spec/Validator/Cart/CartReadyForCheckoutValidatorSpec.php
- src/Controller/Checkout/CompleteOrderAction.php
- src/Resources/config/services/actions/checkout.xml
- src/Resources/config/services/validators/cart.xml
- src/Resources/config/validation/checkout/CompleteOrderRequest.xml
- src/Resources/translations/validators.en.yml
- src/Validator/Cart/CartReadyForCheckoutValidator.php
- src/Validator/Constraints/CartReadyForCheckout.php
- tests/Controller/Checkout/CompleteOrderApiTest.php
- tests/Responses/Expected/checkout/cart_does_not_exist.json
- tests/Responses/Expected/checkout/cart_not_ready_for_checkout.json
The first step to fix https://github.com/Sylius/ShopApiPlugin/issues/598 is to perform validation in `CompleteOrderAction`
> Validate complete order request

- CHANGELOG.md
- UPGRADE.md
> Improve documentation

- tests/Controller/Checkout/CompleteOrderApiTest.php
- tests/DataFixtures/ORM/shipping.yml
- tests/DataFixtures/ORM/shop.yml
- tests/Responses/Expected/checkout/get_available_shipping_methods.json
- tests/Responses/Expected/product/product_list_latest_4_response.json
> Adding a test for skipped shipping and payment.

- README.md
- UPGRADE.md
- doc/swagger.yml
- tests/Controller/AddressBook/UpdateAddressApiTest.php
Protect Address book and me routes in security.yaml 
related issues #569
> Protect Address Book and me routes

- composer.json
> Fixing the ecs dependency problems

- spec/Validator/Cart/CartReadyForCheckoutValidatorSpec.php
- src/Resources/translations/validators.en.yml
- src/Validator/Cart/CartReadyForCheckoutValidator.php
- src/Validator/Constraints/CartReadyForCheckout.php
- tests/Responses/Expected/checkout/cart_not_ready_for_checkout.json
> More comprehensive error messages for checkout validation

- UPGRADE.md
- doc/swagger.yml
- spec/Handler/Customer/GenerateResetPasswordTokenHandlerSpec.php
- spec/Handler/Customer/SendResetPasswordTokenHandlerSpec.php
- src/Controller/Customer/RequestPasswordResettingAction.php
- src/Exception/UserNotFoundException.php
- src/Handler/Customer/GenerateResetPasswordTokenHandler.php
- src/Handler/Customer/SendResetPasswordTokenHandler.php
- src/Resources/config/services/actions/customer.xml
- src/Resources/config/validation/customer/GenerateResetPasswordTokenRequest.xml
- tests/Controller/Customer/RequestPasswordResettingApiTest.php
- tests/Responses/Expected/customer/request_reset_password_empty_email.json
- tests/Responses/Expected/customer/request_reset_password_failed_email.json
Add email Validation to RequestResetPassword
#618
> Add email validation to RequestResetPassword

- doc/swagger.yml
- src/Command/Customer/RegisterCustomer.php
- src/Event/CustomerRegistered.php
- src/Handler/Customer/RegisterCustomerHandler.php
- src/Request/Customer/RegisterCustomerRequest.php
> Add phoneNumber ans subscribedToNewsletter to /register

- .travis.yml
- composer.json
- doc/Cookbook.md
I added some use statements to the cookbook so that people know which classes are the right ones.
This validates 
* the XML (only syntax)
* the fact that the code is valid (linting)
* the use statements that I added
> Adding a documentation validator to the project

- spec/EventListener/CartBlamerListenerSpec.php
- src/EventListener/CartBlamerListener.php
If the login was from the console we don't want to assign a cart to the user object.
> Fixes #657

- README.md
- doc/Cookbook.md
Fixing a typo and clarifying the documentation.
> Fixing a typo in the documentation

- doc/swagger.yml
> Fixing cart item definition

- .travis.yml
- composer.json
- etc/travis/sylius17/bundles.php
- etc/travis/sylius17/doctrine_migrations.yaml
- etc/travis/sylius17/security.yaml
- src/Handler/Cart/PutSimpleItemToCartHandler.php
- tests/Application/config/bundles.php
- tests/Application/config/packages/doctrine_migrations.yaml
- tests/Application/config/packages/security.yaml
- tests/Application/config/packages/security_checker.yaml
- tests/Application/config/packages/sonata_core.yaml
- tests/Application/config/packages/test_cached/doctrine.yaml
- tests/Controller/Cart/SummarizeApiTest.php
> [Maintenance] Update dependencies versions

- spec/Handler/Cart/ChoosePaymentMethodHandlerSpec.php
- src/Handler/Cart/ChoosePaymentMethodHandler.php
- src/Resources/config/services/handler/cart.xml
> Adding an assertion that the payment method needs to be available.

- .github/workflows/build.yml
- composer.json
- spec/Validator/Cart/CartEligibilityValidatorSpec.php
- tests/Application/Kernel.php
Support to PHP 8.1, drop support to PHP 7.4, bump to Sylius 1.10
> [Maintenance] Support PHP 8.1, drop PHP 7.4, bump to Sylius 1.10
